---
language: java
script: |
    if [[ "$RELEASE_BUILD" == 'true' && "$TRAVIS_SECURE_ENV_VARS" == 'true' ]] ; then
      mvn deploy
    else
      mvn test
    fi
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
env:
  global:
    - secure: NKDOZ8D+GbTpoM0uiI8gWskE2kAKWpPKhs3/uJjmgkorkkG1JmWR5XOVVnvz4epBYETuuauAyAmDD58y8iFS9Bh74H6pJs9slZOgy4vO7t1yEu7QB/sdqn8FN/w+IWda9NO9YhhZ/piDxZUk/ttpIiOZgSWUizMBZx/lcDmJK94= # AWS_ACCESS_KEY
    - secure: CobYK3TnNxOWNlLfvnv93tIt/xjFbRYsfBn+5l/l2UMli/uFoYTQVRQWyiWdvW/mgKUiYKPhloqwueNNWgBteS7NCX0PCQwO/9k/PQhOQ4A0/M3Jzbn8aG2Cd9Ai3XmhQpFVwA48JCwlNUqG0INZssFZ9l9oUOZyIyRByypyr/A= # AWS_ACCESS_KEY
  matrix:
    - RELEASE_BUILD=true
    - QUICK_BUILD=true
matrix:
  exclude:
    - jdk: openjdk6
      env: RELEASE_BUILD=true
    - jdk: openjdk6
    - jdk: oraclejdk8
      env: RELEASE_BUILD=true
    - jdk: oraclejdk8
