language: java
script: |
  if [[ "$RELEASE_BUILD" == 'true' && "$TRAVIS_SECURE_ENV_VARS" == 'true' ]] ; then
    mvn deploy
  else
    mvn test
  fi
jdk:
  - openjdk7
  - oraclejdk8
env:
  global:
  - secure: NLOleRANVTErubOCrf3AnljVYxzrz3Os5atObx4cc1J10JUszNYY0QhNiv+2rlK96fHdER7fkf+s+FnaQcisDDUSFMZgzNAdlFvruPnwBBw/3qHLGix0UiTLP/jc6nWQK77hFwsprHvmVdlCMymHQpm9Gw917rTg21kOEM50w98= # ARTIFACTORY_USERNAME
  - secure: Xfi7xKtxB80gOOHbJa2fnxrheWSwLDjUk6sidex1pQuxUq/8F8TsdFuaZs8VTCeSiMXfV90YBV1PP0TNderAInPLy3VYuiUckiqTaqGkRBDrHXcdnQjVdoT86Wzf7ONXcqENtKKrmXTTUQ7zWk0KV/2ePy30LAilBPzA4TF9lJI= # ARTIFACTORY_PASSWORD
  matrix:
  - RELEASE_BUILD=true
  - QUICK_BUILD=true
matrix:
  exclude:
    - jdk: oraclejdk8
      env: RELEASE_BUILD=true
